
[MultivariateStats.ICA]
":name" = "ICA"
":package_name" = "MultivariateStats"
":package_url" = "https://github.com/JuliaStats/MultivariateStats.jl"
":package_uuid" = "6f286f6a-111f-5878-ab1e-185364afe411"
":load_path" = "MLJModels.MultivariateStats_.ICA"
":is_wrapper" = "`false`"
":is_pure_julia" = "`true`"
":is_supervised" = "`false`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":output_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"

[MultivariateStats.RidgeRegressor]
":name" = "RidgeRegressor"
":package_name" = "MultivariateStats"
":package_url" = "https://github.com/JuliaStats/MultivariateStats.jl"
":package_license" = "unkown"
":load_path" = "MLJModels.MultivariateStats_.RidgeRegressor"
":is_wrapper" = "`false`"
":is_pure_julia" = "`true`"
":package_uuid" = "6f286f6a-111f-5878-ab1e-185364afe411"
":supports_weights" = "`false`"
":is_supervised" = "`true`"
":is_probabilistic" = "`false`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":target_scitype" = "`AbstractArray{Continuous,1}`"

[MultivariateStats.KernelPCA]
":name" = "KernelPCA"
":package_name" = "MultivariateStats"
":package_url" = "https://github.com/JuliaStats/MultivariateStats.jl"
":package_uuid" = "6f286f6a-111f-5878-ab1e-185364afe411"
":load_path" = "MLJModels.MultivariateStats_.KernelPCA"
":is_wrapper" = "`false`"
":is_pure_julia" = "`true`"
":is_supervised" = "`false`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":output_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"

[MultivariateStats.PCA]
":name" = "PCA"
":package_name" = "MultivariateStats"
":package_url" = "https://github.com/JuliaStats/MultivariateStats.jl"
":package_uuid" = "6f286f6a-111f-5878-ab1e-185364afe411"
":load_path" = "MLJModels.MultivariateStats_.PCA"
":is_wrapper" = "`false`"
":is_pure_julia" = "`true`"
":is_supervised" = "`false`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":output_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"

[DecisionTree.DecisionTreeRegressor]
":name" = "DecisionTreeRegressor"
":package_name" = "DecisionTree"
":package_url" = "https://github.com/bensadeghi/DecisionTree.jl"
":package_license" = "unkown"
":load_path" = "MLJModels.DecisionTree_.DecisionTreeRegressor"
":is_wrapper" = "`false`"
":is_pure_julia" = "`true`"
":package_uuid" = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
":supports_weights" = "`false`"
":is_supervised" = "`true`"
":is_probabilistic" = "`false`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":target_scitype" = "`AbstractArray{_s163,1} where _s163<:Finite`"

[DecisionTree.DecisionTreeClassifier]
":name" = "DecisionTreeClassifier"
":package_name" = "DecisionTree"
":package_url" = "https://github.com/bensadeghi/DecisionTree.jl"
":package_license" = "unkown"
":load_path" = "MLJModels.DecisionTree_.DecisionTreeClassifier"
":is_wrapper" = "`false`"
":is_pure_julia" = "`true`"
":package_uuid" = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
":supports_weights" = "`false`"
":is_supervised" = "`true`"
":is_probabilistic" = "`true`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":target_scitype" = "`AbstractArray{_s163,1} where _s163<:Finite`"

[ScikitLearn.SVMRegressor]
":name" = "SVMRegressor"
":package_name" = "ScikitLearn"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_license" = "unkown"
":load_path" = "MLJModels.ScikitLearn_.SVMRegressor"
":is_wrapper" = "`false`"
":is_pure_julia" = "`false`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":supports_weights" = "`false`"
":is_supervised" = "`true`"
":is_probabilistic" = "`false`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":target_scitype" = "`AbstractArray{Continuous,1}`"

[ScikitLearn.SVMNuClassifier]
":name" = "SVMNuClassifier"
":package_name" = "ScikitLearn"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_license" = "unkown"
":load_path" = "MLJModels.ScikitLearn_.SVMNuClassifier"
":is_wrapper" = "`false`"
":is_pure_julia" = "`false`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":supports_weights" = "`false`"
":is_supervised" = "`true`"
":is_probabilistic" = "`false`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":target_scitype" = "`AbstractArray{_s95,1} where _s95<:Finite`"

[ScikitLearn.ElasticNet]
":name" = "ElasticNet"
":package_name" = "ScikitLearn"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_license" = "unkown"
":load_path" = "MLJModels.ScikitLearn_.ElasticNet"
":is_wrapper" = "`false`"
":is_pure_julia" = "`false`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":supports_weights" = "`false`"
":is_supervised" = "`true`"
":is_probabilistic" = "`false`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":target_scitype" = "`AbstractArray{Continuous,1}`"

[ScikitLearn.ElasticNetCV]
":name" = "ElasticNetCV"
":package_name" = "ScikitLearn"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_license" = "unkown"
":load_path" = "MLJModels.ScikitLearn_.ElasticNetCV"
":is_wrapper" = "`false`"
":is_pure_julia" = "`false`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":supports_weights" = "`false`"
":is_supervised" = "`true`"
":is_probabilistic" = "`false`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":target_scitype" = "`AbstractArray{_s163,1} where _s163<:Continuous`"

[ScikitLearn.SVMClassifier]
":name" = "SVMClassifier"
":package_name" = "ScikitLearn"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_license" = "unkown"
":load_path" = "MLJModels.ScikitLearn_.SVMClassifier"
":is_wrapper" = "`false`"
":is_pure_julia" = "`false`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":supports_weights" = "`false`"
":is_supervised" = "`true`"
":is_probabilistic" = "`false`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":target_scitype" = "`AbstractArray{_s95,1} where _s95<:Finite`"

[ScikitLearn.SVMLRegressor]
":name" = "SVMLRegressor"
":package_name" = "ScikitLearn"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_license" = "unkown"
":load_path" = "MLJModels.ScikitLearn_.SVMLRegressor"
":is_wrapper" = "`false`"
":is_pure_julia" = "`false`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":supports_weights" = "`false`"
":is_supervised" = "`true`"
":is_probabilistic" = "`false`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":target_scitype" = "`AbstractArray{Continuous,1}`"

[ScikitLearn.SVMNuRegressor]
":name" = "SVMNuRegressor"
":package_name" = "ScikitLearn"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_license" = "unkown"
":load_path" = "MLJModels.ScikitLearn_.SVMNuRegressor"
":is_wrapper" = "`false`"
":is_pure_julia" = "`false`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":supports_weights" = "`false`"
":is_supervised" = "`true`"
":is_probabilistic" = "`false`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":target_scitype" = "`AbstractArray{Continuous,1}`"

[ScikitLearn.SVMLClassifier]
":name" = "SVMLClassifier"
":package_name" = "ScikitLearn"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_license" = "unkown"
":load_path" = "MLJModels.ScikitLearn_.SVMLClassifier"
":is_wrapper" = "`false`"
":is_pure_julia" = "`false`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":supports_weights" = "`false`"
":is_supervised" = "`true`"
":is_probabilistic" = "`false`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":target_scitype" = "`AbstractArray{_s95,1} where _s95<:Finite`"

[LIBSVM.EpsilonSVR]
":name" = "EpsilonSVR"
":package_name" = "LIBSVM"
":package_url" = "https://github.com/mpastell/LIBSVM.jl"
":package_license" = "unkown"
":load_path" = "MLJModels.LIBSVM_.EpsilonSVR"
":is_wrapper" = "`false`"
":is_pure_julia" = "`false`"
":package_uuid" = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
":supports_weights" = "`false`"
":is_supervised" = "`true`"
":is_probabilistic" = "`false`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":target_scitype" = "`AbstractArray{Continuous,1}`"

[LIBSVM.LinearSVC]
":name" = "LinearSVC"
":package_name" = "LIBSVM"
":package_url" = "https://github.com/mpastell/LIBSVM.jl"
":package_license" = "unkown"
":load_path" = "MLJModels.LIBSVM_.LinearSVC"
":is_wrapper" = "`false`"
":is_pure_julia" = "`false`"
":package_uuid" = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
":supports_weights" = "`false`"
":is_supervised" = "`true`"
":is_probabilistic" = "`false`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":target_scitype" = "`AbstractArray{_s293,1} where _s293<:Finite`"

[LIBSVM.NuSVR]
":name" = "NuSVR"
":package_name" = "LIBSVM"
":package_url" = "https://github.com/mpastell/LIBSVM.jl"
":package_license" = "unkown"
":load_path" = "MLJModels.LIBSVM_.NuSVR"
":is_wrapper" = "`false`"
":is_pure_julia" = "`false`"
":package_uuid" = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
":supports_weights" = "`false`"
":is_supervised" = "`true`"
":is_probabilistic" = "`false`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":target_scitype" = "`AbstractArray{Continuous,1}`"

[LIBSVM.NuSVC]
":name" = "NuSVC"
":package_name" = "LIBSVM"
":package_url" = "https://github.com/mpastell/LIBSVM.jl"
":package_license" = "unkown"
":load_path" = "MLJModels.LIBSVM_.NuSVC"
":is_wrapper" = "`false`"
":is_pure_julia" = "`false`"
":package_uuid" = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
":supports_weights" = "`false`"
":is_supervised" = "`true`"
":is_probabilistic" = "`false`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":target_scitype" = "`AbstractArray{_s293,1} where _s293<:Finite`"

[LIBSVM.SVC]
":name" = "SVC"
":package_name" = "LIBSVM"
":package_url" = "https://github.com/mpastell/LIBSVM.jl"
":package_license" = "unkown"
":load_path" = "MLJModels.LIBSVM_.SVC"
":is_wrapper" = "`false`"
":is_pure_julia" = "`false`"
":package_uuid" = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
":supports_weights" = "`false`"
":is_supervised" = "`true`"
":is_probabilistic" = "`false`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":target_scitype" = "`AbstractArray{_s293,1} where _s293<:Finite`"

[LIBSVM.OneClassSVM]
":name" = "OneClassSVM"
":package_name" = "LIBSVM"
":package_url" = "https://github.com/mpastell/LIBSVM.jl"
":package_uuid" = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
":load_path" = "MLJModels.LIBSVM_.OneClassSVM"
":is_wrapper" = "`false`"
":is_pure_julia" = "`false`"
":is_supervised" = "`false`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":output_scitype" = "`AbstractArray{_s293,1} where _s293<:Finite{2}`"

[Clustering.KMeans]
":name" = "KMeans"
":package_name" = "Clustering"
":package_url" = "https://github.com/JuliaStats/Clustering.jl"
":package_uuid" = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
":load_path" = "MLJModels.Clustering_.KMeans"
":is_wrapper" = "`false`"
":is_pure_julia" = "`true`"
":is_supervised" = "`false`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":output_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"

[Clustering.KMedoids]
":name" = "KMedoids"
":package_name" = "Clustering"
":package_url" = "https://github.com/JuliaStats/Clustering.jl"
":package_uuid" = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
":load_path" = "MLJModels.Clustering_.KMedoids"
":is_wrapper" = "`false`"
":is_pure_julia" = "`true`"
":is_supervised" = "`false`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":output_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"

[GLM.OLSRegressor]
":name" = "OLSRegressor"
":package_name" = "GLM"
":package_url" = "https://github.com/JuliaStats/GLM.jl"
":package_license" = "unkown"
":load_path" = "MLJModels.GLM_.OLSRegressor"
":is_wrapper" = "`false`"
":is_pure_julia" = "`true`"
":package_uuid" = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
":supports_weights" = "`false`"
":is_supervised" = "`true`"
":is_probabilistic" = "`true`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":target_scitype" = "`AbstractArray{Continuous,1}`"

[GLM.GLMCountRegressor]
":name" = "GLMCountRegressor"
":package_name" = "GLM"
":package_url" = "https://github.com/JuliaStats/GLM.jl"
":package_license" = "unkown"
":load_path" = "MLJModels.GLM_.GLMCountRegressor"
":is_wrapper" = "`false`"
":is_pure_julia" = "`true`"
":package_uuid" = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
":supports_weights" = "`false`"
":is_supervised" = "`true`"
":is_probabilistic" = "`true`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":target_scitype" = "`AbstractArray{Count,1}`"

[NaiveBayes.GaussianNBClassifier]
":name" = "GaussianNBClassifier"
":package_name" = "NaiveBayes"
":package_url" = "https://github.com/dfdx/NaiveBayes.jl"
":package_license" = "unkown"
":load_path" = "MLJModels.NaiveBayes_.GaussianNBClassifier"
":is_wrapper" = "`false`"
":is_pure_julia" = "`true`"
":package_uuid" = "9bbee03b-0db5-5f46-924f-b5c9c21b8c60"
":supports_weights" = "`false`"
":is_supervised" = "`true`"
":is_probabilistic" = "`true`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":target_scitype" = "`AbstractArray{_s163,1} where _s163<:Finite`"

[NaiveBayes.MultinomialNBClassifier]
":name" = "MultinomialNBClassifier"
":package_name" = "NaiveBayes"
":package_url" = "https://github.com/dfdx/NaiveBayes.jl"
":package_license" = "unkown"
":load_path" = "MLJModels.NaiveBayes_.MultinomialNBClassifier"
":is_wrapper" = "`false`"
":is_pure_julia" = "`true`"
":package_uuid" = "9bbee03b-0db5-5f46-924f-b5c9c21b8c60"
":supports_weights" = "`false`"
":is_supervised" = "`true`"
":is_probabilistic" = "`true`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Count)`"
":target_scitype" = "`AbstractArray{_s163,1} where _s163<:Finite`"

[XGBoost.XGBoostCount]
":name" = "XGBoostCount"
":package_name" = "XGBoost"
":package_url" = "https://github.com/dmlc/XGBoost.jl"
":package_license" = "unkown"
":load_path" = "MLJModels.XGBoost_.XGBoostCount"
":is_wrapper" = "`false`"
":is_pure_julia" = "`false`"
":package_uuid" = "009559a3-9522-5dbb-924b-0b6ed2b22bb9"
":supports_weights" = "`false`"
":is_supervised" = "`true`"
":is_probabilistic" = "`false`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":target_scitype" = "`AbstractArray{Count,1}`"

[XGBoost.XGBoostRegressor]
":name" = "XGBoostRegressor"
":package_name" = "XGBoost"
":package_url" = "https://github.com/dmlc/XGBoost.jl"
":package_license" = "unkown"
":load_path" = "MLJModels.XGBoost_.XGBoostRegressor"
":is_wrapper" = "`false`"
":is_pure_julia" = "`false`"
":package_uuid" = "009559a3-9522-5dbb-924b-0b6ed2b22bb9"
":supports_weights" = "`false`"
":is_supervised" = "`true`"
":is_probabilistic" = "`false`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":target_scitype" = "`AbstractArray{Continuous,1}`"

[XGBoost.XGBoostClassifier]
":name" = "XGBoostClassifier"
":package_name" = "XGBoost"
":package_url" = "https://github.com/dmlc/XGBoost.jl"
":package_license" = "unkown"
":load_path" = "MLJModels.XGBoost_.XGBoostClassifier"
":is_wrapper" = "`false`"
":is_pure_julia" = "`false`"
":package_uuid" = "009559a3-9522-5dbb-924b-0b6ed2b22bb9"
":supports_weights" = "`false`"
":is_supervised" = "`true`"
":is_probabilistic" = "`true`"
":input_scitype" = "`Table{_s13} where _s13<:(AbstractArray{_s12,1} where _s12<:Continuous)`"
":target_scitype" = "`AbstractArray{_s293,1} where _s293<:Finite`"
